# Button GPIO PINs
BUTTON_BTW_PIN = 18
BUTTON_INTERMISSION_PIN = 24
BUTTON_GOAL_PIN = 12
BUTTON_PENALTY_PIN = 27
BUTTON_POWERPLAY_PIN = 5
BUTTON_USANTHEM_PIN = 13
BUTTON_STOP_PIN = 26
BUTTON_FREEBIRD_PIN = 21

# LED GPIO PINs
LED_BTW_PIN = 23
LED_INTERMISSION_PIN = 25
LED_GOAL_PIN = 16
LED_PENALTY_PIN = 17
LED_POWERPLAY_PIN = 22
LED_USANTHEM_PIN = 6
LED_STOP_PIN = 19